routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', function () {
    if(Auth::check()){
        return redirect(route('forums.index'));
    } else {
        return redirect(route('login'));
    }
})->name('home');

// Search
Route::get('forums/search', 'SearchController@searchForum')->name('forums.search');
Route::get('documents/search', 'SearchController@searchDocument')->name('documents.search');

// Documents 
Route::get('/documents', 'DocumentController@index')->name('documents.index');
Route::resource('documents', 'DocumentController')->except('create');
Route::prefix('documents/{document}')->name('documents.')->group(function () {
    Route::post('comments', 'DocumentCommentController@store')->name('comments.store');
    Route::post('recommend', 'RecommendController@recommendDocument')->name('recommend');
});
// Forums 
Route::resource('forums', 'ForumController')->except('create');

Route::prefix('forums/{forum}')->name('forums.')->group(function () {
    Route::post('comments', 'ForumCommentController@store')->name('comments.store');
    Route::post('recommend', 'RecommendController@recommendForum')->name('recommend');
    Route::post('comments/{comment}/recommend', 'RecommendController@recommendCommentForum')->name('comments.recommend');
});

// Google Auth 
Route::get('google', 'GoogleController@redirect')->name('google');
Route::get('callback/google', 'GoogleController@callback');

// Profil
Route::prefix('profiles')->name('profiles.')->group(function () {
    Route::get('/edit', 'ProfileController@edit')->name('edit');
    Route::post('/edit', 'ProfileController@update')->name('update');
    Route::get('{user}', 'ProfileController@show')->name('show');
});

Route::get('register/complete', 'Auth\CompleteRegisterController@completeRegister')
    ->name('register.complete');
Route::post('register/complete', 'Auth\CompleteRegisterController@storeCompleteRegister')
    ->name('register.complete.store');

app/Document.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;


class Document extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'title', 'description', 'type_id', 'subject_id', 'attachment'
    ];

    public function user() {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function subject() {
        return $this->belongsTo('App\Subject', 'subject_id');
    }

    public function fileArray() {
        $names = explode('|', $this->attachment);

        return collect($names);
    }

    public function type() {
        return $this->belongsTo('App\DocumentType', 'type_id');
    }

    public function comments(){
        return $this->hasMany('App\Comment', 'post_id')->where('type', Comment::TYPE_DOCUMENT);
    }

    public function recommends() {
        return $this->hasMany('App\PostRecommend', 'post_id')
            ->where('type', PostRecommend::TYPE_DOCUMENT)
            ->where('status', PostRecommend::STATUS_RECOMMENDED);
    }
}

app/DocumentType.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class DocumentType extends Model
{
    protected $fillable = [
        'name'
    ];

    public function documents() {
        return $this->hasMany('App\Document');
    }

    public $timestamps = false;

}

app/Http/Controllers/DocumentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\DocumentStoreRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Storage;

use App\Document;
use App\Subject;
use App\Comment;
use App\DocumentType;
use App\PostRecommend;
use App\Services\FileService;
use App\User;
use Illuminate\Support\Facades\DB;

class DocumentController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'auth.complete', 'verified']);
    }

    public function index(Request $request)
    {
        $documents = Document::all();
        $subjects = Subject::all();
        $types = DocumentType::all();
        $firstFiveStudents = User::where('university_id', Auth::user()->university->id)
            ->orderBy('point', 'DESC')
            ->take(5)
            ->get();

        return view('documents.index', compact('documents', 'subjects', 'types', 'firstFiveStudents'));
    }

    public function show(Document $document) 
    {
        return view('documents.show', compact('document'));
    }

    public function store(DocumentStoreRequest $request, FileService $fileService) 
    {
        if($request->hasFile('file')) {
            foreach($request->file('file') as $file) {
                $path[] = $fileService->setFile($file)
                    ->setFolderName('DocumentAttachments')
                    ->upload();
            }

        } else {
            $path = [];
        }
        
        Document::create($request->validated() + [
            'user_id' => Auth::id(),
            'type_id' => $request->type, // jenis dokumen
            'subject_id' => $request->subject,
            'attachment' => implode('|', $path)
        ]);

        return redirect(route('documents.index'))
            ->andNotify('success', 'Dokumen berhasil diunggah!');
    }

    public function delete(Document $document)
    {
        $document->delete();

        return view();
    }
}

resources/views/documents/index.blade.php
@extends('layouts.app', [
    'title' => 'Dokumen'
])

@section('content')
<div class="container-fluid pt-3">
    <div class="row justify-content-center mb-3">
        <div class="col-md-6">
            <x-add-document 
                :subjects="$subjects"
                :types="$types"
            />
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-3 mb-3">
            <x-search-document-form
                :subjects="$subjects"
                :types="$types"
            />
        </div>
        <div class="col-md-6">
            @forelse($documents->sortByDesc('created_at') as $document)
                <x-document-item class="mb-3"
                    :document="$document"   
                />
            @empty
            <div class="w-100 text-center">
                Tidak ada dokumen
            </div>
            @endforelse
        </div>
        <div class="col-md-3 mb-3 d-md-block d-none">
            <x-scoreboard
                :students="$firstFiveStudents"
            />
        </div>
    </div>
</div>
@endsection

resources/views/documents/result.blade.php
@extends('layouts.app')

@section('content')
<div class="container-fluid pt-3">
    <div class="row justify-content-center mb-3">
        <div class="col-md-6">
            <h3 class="mb-0 font-weight-bold">
                {{$documentResults->count()}} Dokumen Ditemukan
            </h3>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-3 mb-3">
            <x-search-document-form
                :subjects="$subjects"
                :types="$types"
            />
        </div>
        <div class="col-md-6">
            @forelse ($documentResults->sortByDesc('created_at') as $document)
                <x-document-item class="mb-3"
                    :document="$document"   
                />
            @empty
                Tidak ada dokumen
            @endforelse
        </div>
        <div class="col-md-3">
            {{-- Scoreboard --}}
        </div>
    </div>
</div>
@endsection

resources/views/documents/show.blade.php
@extends('layouts.app', [
    'title' => $document->title
])

@section('content')
<div class="container pt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-12 d-flex justify-content-between">
                            <div>
                                <a class="badge badge-secondary px-2" href="{{route('documents.search', ['subjectIds' => $document->subject->id])}}">
                                    {{$document->subject->name}}
                                </a>
                                <a class="badge badge-success px-2" 
                                    href="{{route('documents.search', ['typeIds' => $document->type->id])}}">
                                    {{$document->type->name}}
                                </a>
                            </div>
                            <small class="text-truncate">{{$document->created_at->diffForHumans()}}</small>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h4 class="font-weight-bold">
                                {{$document->title}}
                            </h4>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-12">
                            <p class="mb-0">{{$document->description}}</p>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-12">
                            @foreach ($document->fileArray() as $item)
                                <div class="card bg-info text-light mb-2">
                                    <div class="card-body d-flex justify-content-between">
                                        <div>
                                            {{basename($item)}}
                                        </div>
                                        <div>
                                            <a href="{{url(Storage::url($item))}}" target="_blank">
                                                <i class="fas fa-eye text-light"></i>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            @endforeach
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 d-flex justify-content-between align-items-end">
                            <div class="d-flex align-items-center flex-fill" style="min-width: 0">
                                <img style="height: 40px; width:40px; object-fit:cover" src="{{ Avatar::create($document->user->name)->toBase64() }}" alt="..." class="rounded-circle mr-3">
                                <div class="d-flex flex-column flex-fill" style="min-width: 0">
                                    <a href="{{ route('profiles.show', ['user' => $document->user->id]) }}" class="font-weight-bold mb-0 text-truncate">
                                        {{ $document->user->name }}
                                    </a>
                                    <small class="text-truncate">
                                        {{$document->user->majority->name}} 
                                        &#8231; 
                                        {{$document->user->university->name}}
                                    </small>
                                </div>
                            </div>
                            <div class="d-flex align-items-center">
                                <i id="btn-recommend" 
                                    class="{{Auth::user()->recommendDocument($document)->count() ?
                                                (Auth::user()->recommendDocument($document)->first()->status == App\PostRecommend::STATUS_RECOMMENDED ?
                                                    'fas text-danger'
                                                    : 'far')
                                                : 'far'
                                            }} fa-heart mr-1" style="cursor: pointer"></i>
                                <div id="recommend-count" class="d-inline mr-3">
                                    {{$document->recommends->count()}}
                                </div>
                                <i class="far fa-comment-alt mr-1"></i>
                                <div class="comment-count d-inline">
                                    {{$document->comments->count()}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="my-4">
                    <div class="row">
                        <form class="col-12" method="POST" action="{{route('documents.comments.store', $document->id)}}">
                            @csrf
                            <p>Pendapat Saya</p>
                            <div class="d-flex align-items-center mb-3">
                                <img style="height: 40px; width:40px; object-fit:cover" src="{{ Avatar::create(Auth::user()->name)->toBase64() }}" alt="..." class="rounded-circle mr-3">
                                <div class="d-flex flex-column">
                                    <a href="{{ route('profiles.show', ['user' => Auth::user()->id]) }}" class="font-weight-bold mb-0">
                                        {{Auth::user()->name}}
                                    </a>
                                    <small>
                                        {{Auth::user()->majority->name}} 
                                        &#8231; 
                                        {{Auth::user()->university->name}}
                                    </small>
                                </div>
                            </div>
                            <x-inputs.textarea 
                                name="message" 
                                placeholder="Tulis pendapat saya..."
                                rows="2"
                            />
                            <div class="w-100 text-right">
                                <button type="submit" class="btn btn-primary mb-3">Kirim</button>
                            </div>
                        </form>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <p>Pendapat ({{$document->comments->count()}})</p>
                            @forelse ($document->comments as $comment)
                                <div class="mt-5">
                                    <div class="d-flex align-items-start justify-content-between">
                                        <div class="d-flex align-items-center mb-3">
                                            <img style="height: 40px; width:40px; object-fit:cover" src="{{ Avatar::create($comment->user->name)->toBase64() }}" alt="..." class="rounded-circle mr-3">
                                            <div class="d-flex flex-column">
                                                <a href="{{ route('profiles.show', ['user' => $comment->user->id]) }}" class="font-weight-bold mb-0">
                                                    {{$comment->user->name}}
                                                </a>
                                                <small>
                                                    {{$comment->user->majority->name}} 
                                                    &#8231; 
                                                    {{$comment->user->university->name}}
                                                </small>
                                            </div>
                                        </div>
                                        <small>{{$comment->created_at->diffForHumans()}}</small>
                                    </div>
                                    <p class="mb-0">{{$comment->message}}</p>    
                                </div>
                            @empty
                                Tidak ada pendapat.
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
         $(document).ready(function() {
            const btnRecommend = document.getElementById('btn-recommend');

            btnRecommend.addEventListener('click', function(e){
                fetch('{{route('documents.recommend', $document->id)}}', {
                    headers: {
                        "Content-Type": "application/json",
                        "Accept": "application/json, text-plain, */*",
                        "X-Requested-With": "XMLHttpRequest",
                        "X-CSRF-TOKEN": '{{csrf_token()}}'
                        },
                    method: 'post',
                    credentials: "same-origin",
                })
                .then(response => response.json())
                .then((response) => {
                    const recommendCount = response.data.recommendCount;
                    const userRecommend = response.data.userRecommend;
                    const recommendCountDOM = document.getElementById('recommend-count');

                    btnRecommend.classList.toggle('text-danger');
                    btnRecommend.classList.toggle('far');
                    btnRecommend.classList.toggle('fas');
                    recommendCountDOM.textContent = recommendCount;
                })
                .catch(function(error) {
                    console.log(error);
                })
            });
        });
    </script>
@endpush