routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', function () {
    if(Auth::check()){
        return redirect(route('forums.index'));
    } else {
        return redirect(route('login'));
    }
})->name('home');

// Search
Route::get('forums/search', 'SearchController@searchForum')->name('forums.search');
Route::get('documents/search', 'SearchController@searchDocument')->name('documents.search');

// Documents 
Route::get('/documents', 'DocumentController@index')->name('documents.index');
Route::resource('documents', 'DocumentController')->except('create');
Route::prefix('documents/{document}')->name('documents.')->group(function () {
    Route::post('comments', 'DocumentCommentController@store')->name('comments.store');
    Route::post('recommend', 'RecommendController@recommendDocument')->name('recommend');
});
// Forums 
Route::resource('forums', 'ForumController')->except('create');

Route::prefix('forums/{forum}')->name('forums.')->group(function () {
    Route::post('comments', 'ForumCommentController@store')->name('comments.store');
    Route::post('recommend', 'RecommendController@recommendForum')->name('recommend');
    Route::post('comments/{comment}/recommend', 'RecommendController@recommendCommentForum')->name('comments.recommend');
});

// Google Auth 
Route::get('google', 'GoogleController@redirect')->name('google');
Route::get('callback/google', 'GoogleController@callback');

// Profil
Route::prefix('profiles')->name('profiles.')->group(function () {
    Route::get('/edit', 'ProfileController@edit')->name('edit');
    Route::post('/edit', 'ProfileController@update')->name('update');
    Route::get('{user}', 'ProfileController@show')->name('show');
});

Route::get('register/complete', 'Auth\CompleteRegisterController@completeRegister')
    ->name('register.complete');
Route::post('register/complete', 'Auth\CompleteRegisterController@storeCompleteRegister')
    ->name('register.complete.store');

app/Forum.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class Forum extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'user_id', 'title', 'description', 'subject_id', 'attachment'
    ];

    public function user() {
        return $this->belongsTo('App\User', 'user_id');
    }

    public function subjects() {
        $subjectIdCollection = collect(explode(',', $this->subject_id));
        $subjectsCollection = $subjectIdCollection->map(function($id){
            return Subject::findOrFail($id);
        });
        $subjects = (object) [
            'names' => implode(', ', $subjectsCollection->map(function($subject){
                return $subject->name;
            })->toArray()),
            'data' => $subjectsCollection
        ];
        return $subjects;
    }

    public function comments(){
        return $this->hasMany('App\Comment', 'post_id')->where('type', Comment::TYPE_FORUM);
    }

    public function recommends() {
        return $this->hasMany('App\PostRecommend', 'post_id')
            ->where('type', PostRecommend::TYPE_FORUM)
            ->where('status', PostRecommend::STATUS_RECOMMENDED);
    }
}

app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\ForumStoreRequest;
use Illuminate\Support\Facades\Auth;

use App\Forum;
use App\Subject;
use App\Services\FileService;
use App\User;

class ForumController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'auth.complete', 'verified']);
    }

    public function index(Request $request)
    {
        $forums = Forum::all();
        $subjects = Subject::all();
        $firstFiveStudents = User::where('university_id', Auth::user()->university->id)
            ->orderBy('point', 'DESC')
            ->take(5)
            ->get();

        return view('forums.index', compact('forums', 'subjects', 'firstFiveStudents'));
    }

    public function show(Forum $forum){

        return view('forums.show', compact('forum'));
    }

    public function store(ForumStoreRequest $request, FileService $fileService) {
        if($request->hasFile('image')) {
            $path = $fileService->setFile($request->file('image'))
                ->setFolderName('ForumAttachments')
                ->upload();
        } else {
            $path = null;
        }
        
        Forum::create($request->validated() + [
            'user_id' => Auth::id(),
            'subject_id' => implode(',', $request->subjects),
            'attachment' => $path
        ]);



        return redirect(route('forums.index'))
            ->andNotify('success', 'Diskusi berhasil dibuat!')
            ->andNotify('warning', 'Poin anda berkurang 10 poin!');
    }

    public function delete(Forum $forum)
    {
        $forum->delete();

        return view();
    }
}

resources/views/forums/index.blade.php
@extends('layouts.app', [
    'title' => 'Home'
])

@section('content')
<div class="container-fluid pt-3">
    <div class="row justify-content-center mb-3">
        <div class="col-md-6">
            <x-add-discussion :subjects="$subjects"/>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-3 mb-3">
            <x-search-forum-form
                :subjects="$subjects"
            />
        </div>
        <div class="col-md-6">
            @forelse($forums->sortByDesc('created_at') as $forum)
                <x-discussion-item class="mb-3"
                    :forum="$forum"   
                />
            @empty
                <div class="w-100 text-center">
                    Tidak ada diskusi
                </div>
            @endforelse
        </div>
        <div class="col-md-3 mb-3 d-md-block d-none">
            <x-scoreboard
                :students="$firstFiveStudents"
            />
        </div>
    </div>
</div>
@endsection

resources/views/forums/result.blade.php
@extends('layouts.app', [
    'title' => 'Pencarian'
])

@section('content')
<div class="container-fluid pt-3">
    <div class="row justify-content-center mb-3">
        <div class="col-md-6">
            <h3 class="mb-0 font-weight-bold">
                {{$forumResults->count()}} Forum Ditemukan
            </h3>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-3">
            <x-search-forum-form
                :subjects="$subjects"
            />
        </div>
        <div class="col-md-6">
            @forelse ($forumResults->sortByDesc('created_at') as $forum)
                <x-discussion-item class="mb-3"
                    :forum="$forum"   
                />
            @empty
                Tidak ada diskusi
            @endforelse
        </div>
        <div class="col-md-3">
            {{-- Scoreboard --}}
        </div>
    </div>
</div>
@endsection

resources/views/forums/show.blade.php
@extends('layouts.app', [
    'title' =>  $forum->title 
])

@section('content')
<div class="container pt-3">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mb-3">
                <div class="card-body">
                    <div class="row mb-2">
                        <div class="col-12 d-flex justify-content-between">
                            <div>
                                @foreach($forum->subjects()->data as $subject)
                                    <a class="badge badge-secondary px-2" href="{{route('forums.search', ['subjectIds' => $subject->id])}}">
                                        {{$subject->name}}
                                    </a>
                                @endforeach
                            </div>
                            <small class="text-truncate">{{$forum->created_at->diffForHumans()}}</small>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <h4 class="font-weight-bold">
                                {{$forum->title}}
                            </h4>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col-12">
                            <p>{{$forum->description}}</p>
                        </div>
                    </div>
                    @if ($forum->attachment)
                    <div class="row mb-5">
                        <div class="col-12">
                            <img src="{{url(Storage::url($forum->attachment))}}" alt="" class="w-100 rounded">
                        </div>
                    </div>
                    @endif
                    <div class="row">
                        <div class="col-12 d-flex justify-content-between align-items-end">
                            <div class="d-flex align-items-center flex-fill" style="min-width: 0">
                                <img style="height: 40px; width:40px; object-fit:cover" src="{{ Avatar::create($forum->user->name)->toBase64() }}" alt="..." class="rounded-circle mr-3">
                                <div class="d-flex flex-column flex-fill" style="min-width: 0">
                                    <a href="{{ route('profiles.show', ['user' => $forum->user->id ]) }}" class="font-weight-bold mb-0 text-truncate">
                                        {{ $forum->user->name }}
                                    </a>
                                    <small class="text-truncate">
                                        {{$forum->user->majority->name}} 
                                        &#8231; 
                                        {{$forum->user->university->name}}
                                    </small>
                                </div>
                            </div>
                            <div class="d-flex align-items-center">
                                <i id="btn-recommend" 
                                    class="{{Auth::user()->recommendForum($forum)->count() ?
                                                (Auth::user()->recommendForum($forum)->first()->status == App\PostRecommend::STATUS_RECOMMENDED ?
                                                    'fas text-danger'
                                                    : 'far')
                                                : 'far'
                                            }} fa-heart mr-1" style="cursor: pointer"></i>
                                <div id="recommend-count" class="d-inline mr-3">
                                    {{$forum->recommends->count()}}
                                </div>
                                <i class="far fa-comment-alt mr-1"></i>
                                <div class="comment-count d-inline">
                                    {{$forum->comments->count()}}
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="my-4">
                    <div class="row">
                        <form class="col-12" method="POST" action="{{route('forums.comments.store', $forum->id)}}">
                            @csrf
                            <p>Pendapat Saya</p>
                            <div class="d-flex align-items-center mb-3">
                                <img style="height: 40px; width:40px; object-fit:cover" src="{{ Avatar::create(Auth::user()->name)->toBase64() }}" alt="..." class="rounded-circle mr-3">
                                <div class="d-flex flex-column">
                                    <a href="{{ route('profiles.show', ['user' => Auth::user()->id]) }}" class="font-weight-bold mb-0">
                                        {{Auth::user()->name}}
                                    </a>
                                    <small>
                                        {{Auth::user()->majority->name}} 
                                        &#8231; 
                                        {{Auth::user()->university->name}}
                                    </small>
                                </div>
                            </div>
                            <x-inputs.textarea 
                                name="message" 
                                placeholder="Tulis pendapat saya..."
                                rows="2"
                            />
                            <div class="w-100 text-right">
                                <button type="submit" class="btn btn-primary mb-3">Kirim</button>
                            </div>
                        </form>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <p>Pendapat ({{$forum->comments->count()}})</p>
                            @forelse ($forum->comments as $comment)
                                <div class="mt-5">
                                    <div class="d-flex align-items-start justify-content-between">
                                        <div class="d-flex align-items-center mb-3">
                                            <img style="height: 40px; width:40px; object-fit:cover" src="{{ Avatar::create($comment->user->name)->toBase64() }}" alt="..." class="rounded-circle mr-3">
                                            <div class="d-flex flex-column">
                                                <a href="{{ route('profiles.show', ['user' => $comment->user->id]) }}" class="font-weight-bold mb-0">
                                                    {{$comment->user->name}}
                                                </a>
                                                <small>
                                                    {{$comment->user->majority->name}} 
                                                    &#8231; 
                                                    {{$comment->user->university->name}}
                                                </small>
                                            </div>
                                        </div>
                                        <small>{{$comment->created_at->diffForHumans()}}</small>
                                    </div>
                                    <p class="mb-0">{{$comment->message}}</p>    
                                    <div class="float-right">
                                        <i id="btn-recommend-comment" 
                                            data-id="{{ $comment->id }}"
                                            class="btn-recommend-comment {{Auth::user()->recommendCommentForum($comment)->count() ?
                                                        (Auth::user()->recommendCommentForum($comment)->first()->status == App\CommentRecommend::STATUS_RECOMMENDED ?
                                                            'fas text-danger'
                                                            : 'far')
                                                        : 'far'
                                                    }} fa-heart mr-1" style="cursor: pointer"></i>
                                        <div id="recommend-comment-count" class="d-inline recommend-comment-count">
                                            {{$comment->recommends->count()}}
                                        </div>
                                    </div>
                                </div>
                            @empty
                                Tidak ada pendapat.
                            @endforelse
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
    <script>
         $(document).ready(function() {
            // Recommend POST
            const btnRecommend = document.getElementById('btn-recommend');

            btnRecommend.addEventListener('click', function(e){
                fetch('{{route('forums.recommend', $forum->id)}}', {
                    headers: {
                        "Content-Type": "application/json",
                        "Accept": "application/json, text-plain, */*",
                        "X-Requested-With": "XMLHttpRequest",
                        "X-CSRF-TOKEN": '{{csrf_token()}}'
                        },
                    method: 'post',
                    credentials: "same-origin",
                })
                .then(response => response.json())
                .then((response) => {
                    const recommendCount = response.data.recommendCount;
                    const userRecommend = response.data.userRecommend;
                    const recommendCountDOM = document.getElementById('recommend-count');

                    btnRecommend.classList.toggle('text-danger');
                    btnRecommend.classList.toggle('far');
                    btnRecommend.classList.toggle('fas');
                    recommendCountDOM.textContent = recommendCount;
                })
                .catch(function(error) {
                    console.log(error);
                })
            });

            // Recommend COMMENT    
            btnRecommendComments = document.querySelectorAll('.btn-recommend-comment');
            btnRecommendComments.forEach(btn => {
                btn.addEventListener('click', function(e){
                    let comment_id = btn.dataset.id;
                    
                    fetch('/forums/{{$forum->id}}/comments/'+comment_id+'/recommend', {
                        headers: {
                            "Content-Type": "application/json",
                            "Accept": "application/json, text-plain, */*",
                            "X-Requested-With": "XMLHttpRequest",
                            "X-CSRF-TOKEN": '{{csrf_token()}}'
                            },
                        method: 'post',
                        credentials: "same-origin",
                    })
                    .then(response => response.json())
                    .then((response) => {
                        const userRecommendComment = response.data.userRecommend;
                        const recommendCommentCount = response.data.recommendCount;
    
                        btn.classList.toggle('text-danger');
                        btn.classList.toggle('far');
                        btn.classList.toggle('fas');
                        btn.parentElement.querySelector('.recommend-comment-count').textContent = recommendCommentCount;
                    })
                    .catch(function(error) {
                        console.log(error);
                    })
                });
            });
        });
    </script>
@endpush