routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/', function () {
    if(Auth::check()){
        return redirect(route('forums.index'));
    } else {
        return redirect(route('login'));
    }
})->name('home');

// Search
Route::get('forums/search', 'SearchController@searchForum')->name('forums.search');
Route::get('documents/search', 'SearchController@searchDocument')->name('documents.search');

// Documents 
Route::get('/documents', 'DocumentController@index')->name('documents.index');
Route::resource('documents', 'DocumentController')->except('create');
Route::prefix('documents/{document}')->name('documents.')->group(function () {
    Route::post('comments', 'DocumentCommentController@store')->name('comments.store');
    Route::post('recommend', 'RecommendController@recommendDocument')->name('recommend');
});
// Forums 
Route::resource('forums', 'ForumController')->except('create');

Route::prefix('forums/{forum}')->name('forums.')->group(function () {
    Route::post('comments', 'ForumCommentController@store')->name('comments.store');
    Route::post('recommend', 'RecommendController@recommendForum')->name('recommend');
    Route::post('comments/{comment}/recommend', 'RecommendController@recommendCommentForum')->name('comments.recommend');
});

// Google Auth 
Route::get('google', 'GoogleController@redirect')->name('google');
Route::get('callback/google', 'GoogleController@callback');

// Profil
Route::prefix('profiles')->name('profiles.')->group(function () {
    Route::get('/edit', 'ProfileController@edit')->name('edit');
    Route::post('/edit', 'ProfileController@update')->name('update');
    Route::get('{user}', 'ProfileController@show')->name('show');
});

Route::get('register/complete', 'Auth\CompleteRegisterController@completeRegister')
    ->name('register.complete');
Route::post('register/complete', 'Auth\CompleteRegisterController@storeCompleteRegister')
    ->name('register.complete.store');

app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\ProfileUpdateRequest;
use App\Majority;
use App\University;
use Illuminate\Http\Request;
use App\User;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    public function __construct()
    {
        $this->middleware(['auth', 'auth.complete']);
    }

    public function show(User $user){
        $userForums = $user->forums->each(function($forum){
            $forum->activityType = 'forum';
        });
        $userDocuments = $user->documents->each(function($document){
            $document->activityType = 'document';
        });
        $user->activities = $userForums->concat($userDocuments)->sortByDesc('created_at');
        
        return view('profiles.show', compact('user'));
    }
    public function edit(){
        $majorities = Majority::all();
        $universities = University::all();
        return view('profiles.edit', compact('majorities', 'universities'));
    }
    public function update(ProfileUpdateRequest $request){
        Auth::user()->update([
            'name' => $request->name,
            'email' => $request->email,
            'majority_id' => $request->majority,
            'university_id' => $request->university,
        ]);

        return redirect(route('profiles.show', Auth::id()))
            ->andNotify('success', 'Profile berhasil diedit!');
    }
}

resources/views/profiles/edit.blade.php
@extends('layouts.app', [
    'title' => 'Pengaturan Akun'
])

@section('content')
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card card-body">
                    <div class="text-center my-3">
                        <b style="font-size: 1.25rem">Ubah Data Akun</b>
                    </div>
                    <form method="POST" action="{{route('profiles.update')}}" class="card-body" >
                        @csrf
                        <div class="row">
                            <div class="col-md-6">
                                <x-inputs.input 
                                    label="Nama" 
                                    name="name" 
                                    type="text"
                                    :value="Auth::user()->name"
                                    placeholder="Masukkan Nama Anda"
                                    required
                                />
                                <x-inputs.input 
                                    label="Email" 
                                    name="email" 
                                    type="email"
                                    :value="Auth::user()->email"
                                    placeholder="Masukkan Email Anda"
                                    required
                                />
                            </div>
                            <div class="col-md-6">
                                <x-inputs.select 
                                    required 
                                    label="Jurusan" 
                                    name="majority" 
                                    placeholder="Pilih jurusan"
                                    :value="Auth::user()->majority->id"
                                    search
                                    :option-values=" $majorities->map(fn($majority) => $majority->id)"
                                    :option-names=" $majorities->map(fn($majority) => $majority->name)" 
                                />
                                <x-inputs.select 
                                    required 
                                    label="Universitas" 
                                    name="university" 
                                    placeholder="Pilih universitas"
                                    :value="Auth::user()->university->id"
                                    search
                                    :option-values=" $universities->map(fn($university) => $university->id)"
                                    :option-names=" $universities->map(fn($university) => $university->name)" 
                                />
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-12 text-right">
                                <a href="" class="btn btn-secondary mr-2">Ganti Password</a>
                                <a href="{{route('profiles.show', Auth::id())}}" class="btn btn-light mr-2">Batal</a>
                                <button type="submit" class="btn btn-primary">Simpan Perubahan</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/profiles/show.blade.php
@extends('layouts.app', [
    'title' => $user->name
])

@section('content')
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="my-3 d-flex align-items-center flex-md-row flex-column">
                    <div class="m-3">
                        <img style="height: 120px; width:120px; object-fit:cover" src="{{ Avatar::create($user->name)->toBase64() }}" alt="..." class="rounded-circle">
                    </div>
                    <div>
                        <div class="mb-2 d-flex flex-wrap align-items-center justify-content-center justify-content-md-start">
                            <h3 class="font-weight-bold mb-2 mx-2 text-center text-md-left">
                                {{ $user->name }}
                            </h3>
                            @if ($user->id == Auth::id())
                            <div class="d-flex mb-2">
                                <a href="{{route('profiles.edit')}}" class="mx-2 btn btn-outline-primary btn-sm">
                                    <i class="fas fa-edit"></i>
                                    Edit Profil
                                </a>
                                <form action="{{ route('logout') }}" method="POST">
                                    @csrf
                                    <button class="btn btn-outline-danger btn-sm mr-2">Logout</button>
                                </form>
                            </div>
                            @endif
                        </div>
                        <div class="d-flex justify-content-center justify-content-md-start text-center text-md-left mx-2">
                            {{ $user->majority->name }} 
                            &#8231; 
                            {{ $user->university->name }}
                        </div>
                    </div>
                </div>
                <div class="card my-3">
                    <div class="card-body">
                        <small class="text-truncate">Pangkat saya</small>
                        <h4 class="font-weight-bold mb-2 mt-1">
                            {{ $user->rank }}
                        </h4>
                        <div class="text-truncate">
                            {{ $user->point }} Poin &#8231; 
                            {{ $user->forums->count() }} Diskusi &#8231; 
                            {{ $user->comments->count() }} Kontribusi
                        </div>
                    </div>
                </div>
                <div>
                    @forelse ($user->activities as $activity)
                        @if ($activity->activityType == 'forum')
                            <x-discussion-item class="mb-3 border-primary"
                                :forum="$activity"
                            ></x-discussion-item>
                        @else
                            <x-document-item class="mb-3 border-success"
                                :document="$activity"
                            ></x-document-item>
                        @endif
                    @empty
                        Belum ada aktivitas
                    @endforelse
                </div>
            </div>
        </div>
    </div>
@endsection